name: Trigger Jenkins Build with Parameters

on:
  workflow_dispatch:  # Allows manual trigger from GitHub UI with inputs
    inputs:
      BRANCH:
        description: 'Git Branch to Build'
        required: true
        default: 'main'
      DEPLOY_ENV:
        description: 'Deployment Environment'
        required: true
        default: 'staging'
      S3_BUCKET:
        description: 'S3 bucket'
        required: true
        default: 'yotpo-people'
      S3_PATH:
        description: 'S3 filepath'
        required: true
        default: ''

jobs:
  trigger-jenkins:
    runs-on: ubuntu-latest
    steps:
      - name: Construct Jenkins Build URL
        run: |
          JENKINS_URL="${{ secrets.JENKINS_URL }}"
          JENKINS_USER="${{ secrets.JENKINS_USER }}"
          JENKINS_API_TOKEN="${{ secrets.JENKINS_API_TOKEN }}"
          JENKINS_JOB_NAME="${{ secrets.JENKINS_JOB_NAME }}"
          S3_BUCKET="${{ github.event.inputs.S3_BUCKET }}"
          SE_PATH="${{ github.event.inputs.FILE_PATH }}"
          
          BUILD_URL="$JENKINS_URL/job/$JENKINS_JOB_NAME/buildWithParameters?S3_BUCKET=$S3_BUCKET&S3_PATH=$S3_PATH"

          echo "🚀 Jenkins Build URL: $BUILD_URL"

      - name: Trigger Jenkins Build
        run: |
          curl -X POST "$BUILD_URL" --user "$JENKINS_USER:$JENKINS_API_TOKEN"
