name: Trigger Jenkins Build with Parameters

on:
  push:
    branches:
      - main

jobs:
  trigger-jenkins:
    runs-on: ubuntu-latest
    steps:
      - name: Set Jenkins URL
        run: |
          export FULL_BUILD_URL="https://jenkins.example.com/job/your-job-name/buildWithParameters?token=your-token"
          echo "FULL_BUILD_URL=$FULL_BUILD_URL" >> $GITHUB_ENV

      - name: Trigger Jenkins build
        run: |
          curl -X POST "$FULL_BUILD_URL"
        env:
          JENKINS_USER: ${{ secrets.JENKINS_USER }}
          JENKINS_API_TOKEN: ${{ secrets.JENKINS_API_TOKEN }}