name: Trigger Jenkins Build with Parameters

on:
  workflow_dispatch:  # Allows manual trigger from GitHub UI with inputs
    inputs:
      BRANCH:
        description: 'Git Branch to Build'
        required: true
        default: 'main'
      DEPLOY_ENV:
        description: 'Deployment Environment'
        required: true
        default: 'staging'
      S3_BUCKET:
        description: 'S3 bucket'
        required: true
        default: 'yotpo-people'
      S3_PATH:
        description: 'S3 filepath'
        required: true
        default: 'justin_farris/multicurrency2025-02-02T21-54-02.csv'

jobs:
  trigger-jenkins:
    runs-on: ubuntu-latest
    steps:
      - name: Construct Jenkins Build URL
        run: |
          JENKINS_USER="$JENKINS_USER"
          JENKINS_API_TOKEN="$JENKINS_API_TOKEN"
          FULL_BUILD_URL="$BUILD_URL"

          echo "🚀 Jenkins Build URL: $FULL_BUILD_URL"
        env:
          JENKINS_USER: ${{ secrets.JENKINS_USER }}
          JENKINS_API_TOKEN: ${{ secrets.JENKINS_API_TOKEN }}
          BUILD_URL: ${{ secrets.BUILD_URL }}

      - name: Trigger Jenkins Build
        run: |
          curl -X POST "$FULL_BUILD_URL"
