name: Trigger Jenkins Build with Parameters

on:
  workflow_dispatch:  # Allows manual trigger from GitHub UI with inputs
    inputs:
      BRANCH:
        description: 'Git Branch to Build'
        required: true
        default: 'main'
      DEPLOY_ENV:
        description: 'Deployment Environment'
        required: true
        default: 'staging'

jobs:
  trigger-jenkins:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger Jenkins Build with Parameters
        run: |
          JENKINS_URL="${{ secrets.JENKINS_URL }}"
          JENKINS_USER="${{ secrets.JENKINS_USER }}"
          JENKINS_API_TOKEN="${{ secrets.JENKINS_API_TOKEN }}"
          JENKINS_JOB_NAME="${{ secrets.JENKINS_JOB_NAME }}"
          S3_BUCKET="yotpo-people"
          SE_PATH="${{ github.event.inputs.FILE_PATH }}"
          
          BUILD_URL="$JENKINS_URL/job/$JENKINS_JOB_NAME/buildWithParameters?BRANCH=$BRANCH&DEPLOY_ENV=$DEPLOY_ENV"

          curl -X POST "$BUILD_URL" --user "$JENKINS_USER:$JENKINS_API_TOKEN"
